### ISSUE TITLE
Too much errors

### ISSUE THREAD

**Issue by stdex** [AtomLinter/linter-javac#29] opened 2015-08-05 23:00 UTC
![image](https://cloud.githubusercontent.com/assets/4608879/9100015/c0bd134a-3bde-11e5-92a9-85b9222e5721.png)

**Comment by steelbrain** [comment] 2015-08-05 23:01
Can you compare the output of `linter-javac` and `javac` cli and tell us if they are different?

**Comment by daw42** [comment] 2015-08-05 23:02
This is probably the classpath issue that should be fixed by #26 and #27.

**Comment by stdex** [comment] 2015-08-05 23:12
@steelbrain: output's are same, but I expected a different behavior...
In intellij I have no errors for this class.

**Comment by k2b6s9j** [comment] 2015-08-05 23:57
The issue is Maven provides the Java compiler everything needed for a successful compilation. This package sends the current file directly to the Java compiler. In this instance having you set up the Linter to match your Maven instance would not be worth your time or ours. A Linter provider for Maven projects is coming. I will release before the end of August.

**Closed by k2b6s9j** 2015-08-05 23:57 UTC

**Comment by k2b6s9j** [comment] 2015-08-05 23:59
Don't feel too bad. This issue exists with all project based Java projects (Maven, Ant, Gradle, etc.)

**Comment by k2b6s9j** [comment] 2015-08-06 00:03
@steelbrain As per your question. The output of `linter-javac` and `javac` would be identical. Herein lies the problem. @stdex is expected `linter-javac
